COUNTRY_PROFILES = {
    "vietnam": {
        "iso2": "VN",
        "iso3": "VNM",
        "comtrade_reporter_code": "704",
        "currency": "VND",
        "capital": "Hanoi",
        "lat": 21.0285,
        "lon": 105.8542,
    },
    "india": {
        "iso2": "IN",
        "iso3": "IND",
        "comtrade_reporter_code": "699",
        "currency": "INR",
        "capital": "New Delhi",
        "lat": 28.6139,
        "lon": 77.2090,
    },
    "indonesia": {
        "iso2": "ID",
        "iso3": "IDN",
        "comtrade_reporter_code": "360",
        "currency": "IDR",
        "capital": "Jakarta",
        "lat": -6.2088,
        "lon": 106.8456,
    },
    "mexico": {
        "iso2": "MX",
        "iso3": "MEX",
        "comtrade_reporter_code": "484",
        "currency": "MXN",
        "capital": "Mexico City",
        "lat": 19.4326,
        "lon": -99.1332,
    },
    "germany": {
        "iso2": "DE",
        "iso3": "DEU",
        "comtrade_reporter_code": "276",
        "currency": "EUR",
        "capital": "Berlin",
        "lat": 52.52,
        "lon": 13.405,
    },
    "united states": {
        "iso2": "US",
        "iso3": "USA",
        "comtrade_reporter_code": "842",
        "currency": "USD",
        "capital": "Washington, DC",
        "lat": 38.9072,
        "lon": -77.0369,
    },
    "china": {
        "iso2": "CN",
        "iso3": "CHN",
        "comtrade_reporter_code": "156",
        "currency": "CNY",
        "capital": "Beijing",
        "lat": 39.9042,
        "lon": 116.4074,
    },
    "japan": {
        "iso2": "JP",
        "iso3": "JPN",
        "comtrade_reporter_code": "392",
        "currency": "JPY",
        "capital": "Tokyo",
        "lat": 35.6762,
        "lon": 139.6503,
    },
    "south korea": {
        "iso2": "KR",
        "iso3": "KOR",
        "comtrade_reporter_code": "410",
        "currency": "KRW",
        "capital": "Seoul",
        "lat": 37.5665,
        "lon": 126.9780,
    },
    "singapore": {
        "iso2": "SG",
        "iso3": "SGP",
        "comtrade_reporter_code": "702",
        "currency": "SGD",
        "capital": "Singapore",
        "lat": 1.3521,
        "lon": 103.8198,
    },
    "thailand": {
        "iso2": "TH",
        "iso3": "THA",
        "comtrade_reporter_code": "764",
        "currency": "THB",
        "capital": "Bangkok",
        "lat": 13.7563,
        "lon": 100.5018,
    },
    "malaysia": {
        "iso2": "MY",
        "iso3": "MYS",
        "comtrade_reporter_code": "458",
        "currency": "MYR",
        "capital": "Kuala Lumpur",
        "lat": 3.1390,
        "lon": 101.6869,
    },
    "philippines": {
        "iso2": "PH",
        "iso3": "PHL",
        "comtrade_reporter_code": "608",
        "currency": "PHP",
        "capital": "Manila",
        "lat": 14.5995,
        "lon": 120.9842,
    },
    "australia": {
        "iso2": "AU",
        "iso3": "AUS",
        "comtrade_reporter_code": "036",
        "currency": "AUD",
        "capital": "Canberra",
        "lat": -35.2809,
        "lon": 149.1300,
    },
    "united kingdom": {
        "iso2": "GB",
        "iso3": "GBR",
        "comtrade_reporter_code": "826",
        "currency": "GBP",
        "capital": "London",
        "lat": 51.5072,
        "lon": -0.1276,
    },
    "france": {
        "iso2": "FR",
        "iso3": "FRA",
        "comtrade_reporter_code": "250",
        "currency": "EUR",
        "capital": "Paris",
        "lat": 48.8566,
        "lon": 2.3522,
    },
    "italy": {
        "iso2": "IT",
        "iso3": "ITA",
        "comtrade_reporter_code": "380",
        "currency": "EUR",
        "capital": "Rome",
        "lat": 41.9028,
        "lon": 12.4964,
    },
    "spain": {
        "iso2": "ES",
        "iso3": "ESP",
        "comtrade_reporter_code": "724",
        "currency": "EUR",
        "capital": "Madrid",
        "lat": 40.4168,
        "lon": -3.7038,
    },
    "canada": {
        "iso2": "CA",
        "iso3": "CAN",
        "comtrade_reporter_code": "124",
        "currency": "CAD",
        "capital": "Ottawa",
        "lat": 45.4215,
        "lon": -75.6972,
    },
    "brazil": {
        "iso2": "BR",
        "iso3": "BRA",
        "comtrade_reporter_code": "076",
        "currency": "BRL",
        "capital": "Brasilia",
        "lat": -15.7939,
        "lon": -47.8828,
    },
    "south africa": {
        "iso2": "ZA",
        "iso3": "ZAF",
        "comtrade_reporter_code": "710",
        "currency": "ZAR",
        "capital": "Pretoria",
        "lat": -25.7479,
        "lon": 28.2293,
    },
    "turkey": {
        "iso2": "TR",
        "iso3": "TUR",
        "comtrade_reporter_code": "792",
        "currency": "TRY",
        "capital": "Ankara",
        "lat": 39.9334,
        "lon": 32.8597,
    },
    "united arab emirates": {
        "iso2": "AE",
        "iso3": "ARE",
        "comtrade_reporter_code": "784",
        "currency": "AED",
        "capital": "Abu Dhabi",
        "lat": 24.4539,
        "lon": 54.3773,
    },
    "saudi arabia": {
        "iso2": "SA",
        "iso3": "SAU",
        "comtrade_reporter_code": "682",
        "currency": "SAR",
        "capital": "Riyadh",
        "lat": 24.7136,
        "lon": 46.6753,
    },
    "bangladesh": {
        "iso2": "BD",
        "iso3": "BGD",
        "comtrade_reporter_code": "050",
        "currency": "BDT",
        "capital": "Dhaka",
        "lat": 23.8103,
        "lon": 90.4125,
    },
    "pakistan": {
        "iso2": "PK",
        "iso3": "PAK",
        "comtrade_reporter_code": "586",
        "currency": "PKR",
        "capital": "Islamabad",
        "lat": 33.6844,
        "lon": 73.0479,
    },
    "netherlands": {
        "iso2": "NL",
        "iso3": "NLD",
        "comtrade_reporter_code": "528",
        "currency": "EUR",
        "capital": "Amsterdam",
        "lat": 52.3676,
        "lon": 4.9041,
    },
    "poland": {
        "iso2": "PL",
        "iso3": "POL",
        "comtrade_reporter_code": "616",
        "currency": "PLN",
        "capital": "Warsaw",
        "lat": 52.2297,
        "lon": 21.0122,
    },
}


def normalize_country_name(country: str) -> str:
    return " ".join(country.strip().lower().split())


def get_country_profile(country: str) -> dict:
    key = normalize_country_name(country)
    profile = COUNTRY_PROFILES.get(key)
    if profile:
        return {"name": country.strip().title(), **profile}

    return {
        "name": country.strip().title(),
        "iso2": "",
        "iso3": "",
        "comtrade_reporter_code": "",
        "currency": "",
        "capital": "",
        "lat": 0,
        "lon": 0,
    }
